### ISSUE TITLE
Create UI design for the project

### ISSUE THREAD

**Issue by rusiruavb** [ms-club-sliit/minihackathon-2022#12]
Need to build the design for website. @miyurugunarathna once you finish the design, share the Figma link as a comment for this issue.

**Comment by miyurugunarathna** [comment]
> Need to build the design for website. @miyurugunarathna once you finish the design, share the Figma link as a comment for this issue.

Sure. 👍

**Comment by rusiruavb** [comment]
@ms-club-sliit/dev-team @miyurugunarathna has complete the design of the website. Use this **[Figma link](https://www.figma.com/file/ULDxGnPhicUkcUPZ7jXPMw/Mini-Hackathon-Web?node-id=0%3A1)** to view the design. Amazing work @miyurugunarathna 🔥. Nicely done 👌🏼
